import type { Product, Category, Review, User, Order } from '../types';

// Mock Products Data
export const products: Product[] = [
  {
    id: '1',
    name: 'MacBook Pro 16" M3 Max',
    description: 'The most powerful MacBook Pro ever with the M3 Max chip. Features an incredible 16-inch Liquid Retina XDR display, up to 22 hours of battery life, and advanced thermal architecture.',
    price: 3499,
    originalPrice: 3999,
    category: 'Laptops',
    brand: 'Apple',
    rating: 4.9,
    reviewCount: 847,
    stock: 24,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
      'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800',
    ],
    specifications: {
      'Processor': 'Apple M3 Max 16-core',
      'RAM': '48GB Unified Memory',
      'Storage': '1TB SSD',
      'Display': '16.2" Liquid Retina XDR',
      'Graphics': '40-core GPU',
      'Battery': 'Up to 22 hours',
      'Weight': '2.16 kg',
    },
    tags: ['professional', 'creative', 'premium'],
    featured: true,
    isNew: true,
  },
  {
    id: '2',
    name: 'Dell XPS 15 OLED',
    description: 'Stunning OLED display meets powerful performance. The XPS 15 features Intel Core i9 processor, NVIDIA RTX graphics, and a breathtaking 3.5K OLED touchscreen.',
    price: 2299,
    originalPrice: 2599,
    category: 'Laptops',
    brand: 'Dell',
    rating: 4.7,
    reviewCount: 523,
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1593642632823-8f78536788c6?w=800',
      'https://images.unsplash.com/photo-1588872657578-a3d2af9f8595?w=800',
    ],
    specifications: {
      'Processor': 'Intel Core i9-13900H',
      'RAM': '32GB DDR5',
      'Storage': '1TB NVMe SSD',
      'Display': '15.6" 3.5K OLED Touch',
      'Graphics': 'NVIDIA RTX 4070',
      'Battery': 'Up to 10 hours',
      'Weight': '2.0 kg',
    },
    tags: ['professional', 'oled', 'touchscreen'],
    featured: true,
  },
  {
    id: '3',
    name: 'iPhone 15 Pro Max',
    description: 'The ultimate iPhone with titanium design, A17 Pro chip, and the most advanced camera system ever. Features a 6.7-inch Super Retina XDR display with ProMotion.',
    price: 1199,
    originalPrice: 1299,
    category: 'Smartphones',
    brand: 'Apple',
    rating: 4.8,
    reviewCount: 1243,
    stock: 56,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2069?w=800',
      'https://images.unsplash.com/photo-1592286927505-b0e2cv154b9j?w=800',
    ],
    specifications: {
      'Display': '6.7" Super Retina XDR',
      'Processor': 'A17 Pro chip',
      'Storage': '256GB',
      'Camera': '48MP Main, 12MP Ultra Wide',
      'Battery': 'Up to 29 hours video',
      'Material': 'Titanium frame',
    },
    tags: ['premium', '5g', 'pro'],
    featured: true,
    isNew: true,
  },
  {
    id: '4',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Galaxy AI is here. The S24 Ultra features an advanced AI chip, 200MP camera, S Pen integration, and a stunning 6.8-inch Dynamic AMOLED display.',
    price: 1299,
    originalPrice: 1419,
    category: 'Smartphones',
    brand: 'Samsung',
    rating: 4.7,
    reviewCount: 892,
    stock: 42,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800',
      'https://images.unsplash.com/photo-1565849904461-04a58ad397e4?w=800',
    ],
    specifications: {
      'Display': '6.8" Dynamic AMOLED 2X',
      'Processor': 'Snapdragon 8 Gen 3',
      'Storage': '512GB',
      'Camera': '200MP Quad Camera',
      'Battery': '5000mAh',
      'Features': 'S Pen included',
    },
    tags: ['ai', 's-pen', 'android'],
    featured: true,
  },
  {
    id: '5',
    name: 'Sony WH-1000XM5',
    description: 'Industry-leading noise cancellation with exceptional sound quality. The WH-1000XM5 features 30-hour battery life, crystal-clear calls, and ultra-comfortable design.',
    price: 349,
    originalPrice: 399,
    category: 'Audio',
    brand: 'Sony',
    rating: 4.8,
    reviewCount: 2156,
    stock: 89,
    images: [
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    ],
    specifications: {
      'Type': 'Over-ear',
      'Noise Cancellation': 'Active (Industry-leading)',
      'Battery': 'Up to 30 hours',
      'Connectivity': 'Bluetooth 5.2',
      'Weight': '250g',
      'Features': 'Speak-to-Chat, LDAC',
    },
    tags: ['wireless', 'noise-cancelling', 'premium'],
    featured: true,
  },
  {
    id: '6',
    name: 'AirPods Pro (2nd Gen)',
    description: 'Up to 2x more Active Noise Cancellation. Adaptive Transparency. Personalized Spatial Audio. The ultimate listening experience in a compact design.',
    price: 249,
    originalPrice: 279,
    category: 'Audio',
    brand: 'Apple',
    rating: 4.7,
    reviewCount: 3421,
    stock: 124,
    images: [
      'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800',
      'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=800',
    ],
    specifications: {
      'Type': 'In-ear',
      'Noise Cancellation': 'Active (2x improved)',
      'Battery': 'Up to 6 hours (ANC on)',
      'Charging': 'MagSafe, Wireless',
      'Features': 'Adaptive Audio, Conversation Awareness',
    },
    tags: ['wireless', 'apple', 'spatial-audio'],
    featured: true,
  },
  {
    id: '7',
    name: 'iPad Pro 12.9" M2',
    description: 'The ultimate iPad experience with M2 chip, stunning Liquid Retina XDR display, and pro cameras. Perfect for creative professionals and power users.',
    price: 1099,
    originalPrice: 1199,
    category: 'Tablets',
    brand: 'Apple',
    rating: 4.9,
    reviewCount: 678,
    stock: 31,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800',
      'https://images.unsplash.com/photo-1561154464-81e56c4a8d6c?w=800',
    ],
    specifications: {
      'Display': '12.9" Liquid Retina XDR',
      'Processor': 'Apple M2 chip',
      'Storage': '128GB',
      'Camera': '12MP Wide, 10MP Ultra Wide',
      'Battery': 'Up to 10 hours',
      'Connectivity': 'Wi-Fi 6E, 5G optional',
    },
    tags: ['professional', 'creative', 'tablet'],
    featured: true,
  },
  {
    id: '8',
    name: 'Samsung Galaxy Tab S9 Ultra',
    description: 'The largest Galaxy Tab ever with a stunning 14.6-inch AMOLED display. Includes S Pen and features Snapdragon 8 Gen 2 for unmatched Android tablet performance.',
    price: 1199,
    originalPrice: 1319,
    category: 'Tablets',
    brand: 'Samsung',
    rating: 4.6,
    reviewCount: 412,
    stock: 22,
    images: [
      'https://images.unsplash.com/photo-1560159752-d6d28a88c8f6?w=800',
      'https://images.unsplash.com/photo-1593159531610-4c4f6f6d7f0e?w=800',
    ],
    specifications: {
      'Display': '14.6" Super AMOLED',
      'Processor': 'Snapdragon 8 Gen 2',
      'Storage': '256GB',
      'RAM': '12GB',
      'Battery': '11,200mAh',
      'Features': 'S Pen included, IP68',
    },
    tags: ['android', 's-pen', 'large-screen'],
    isNew: true,
  },
  {
    id: '9',
    name: 'Apple Watch Ultra 2',
    description: 'The most rugged and capable Apple Watch ever. Built for endurance athletes, outdoor adventurers, and water sports enthusiasts with precision GPS.',
    price: 799,
    originalPrice: 849,
    category: 'Wearables',
    brand: 'Apple',
    rating: 4.8,
    reviewCount: 534,
    stock: 45,
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800',
    ],
    specifications: {
      'Display': '49mm Always-On Retina',
      'Case': 'Titanium',
      'Battery': 'Up to 36 hours',
      'Water Resistance': '100m',
      'Features': 'Precision GPS, Siren, Action Button',
    },
    tags: ['fitness', 'outdoor', 'premium'],
    featured: true,
  },
  {
    id: '10',
    name: 'Garmin Fenix 7X Pro',
    description: 'The ultimate multisport GPS watch with solar charging, advanced training metrics, and rugged design. Built for athletes who demand the best.',
    price: 899,
    originalPrice: 999,
    category: 'Wearables',
    brand: 'Garmin',
    rating: 4.7,
    reviewCount: 287,
    stock: 0,
    images: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800',
      'https://images.unsplash.com/photo-1521405924368-66d80f9d4a8a?w=800',
    ],
    specifications: {
      'Display': '1.4" Always-on',
      'Battery': 'Up to 37 days (smartwatch mode)',
      'Solar': 'Power Glass solar charging',
      'Maps': 'TopoActive Europe',
      'Features': 'Training Readiness, HRV Status',
    },
    tags: ['fitness', 'solar', 'outdoor'],
  },
  {
    id: '11',
    name: 'LG C3 65" OLED evo TV',
    description: 'Experience perfect blacks and infinite contrast with OLED evo technology. Features α9 AI Processor 4K, Dolby Vision IQ, and NVIDIA G-SYNC for gaming.',
    price: 1799,
    originalPrice: 2499,
    category: 'TVs',
    brand: 'LG',
    rating: 4.8,
    reviewCount: 623,
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800',
      'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=800',
    ],
    specifications: {
      'Display': '65" OLED evo',
      'Resolution': '4K Ultra HD',
      'HDR': 'Dolby Vision IQ, HDR10',
      'Refresh Rate': '120Hz',
      'Smart TV': 'webOS 23',
      'Gaming': 'NVIDIA G-SYNC, 4x HDMI 2.1',
    },
    tags: ['oled', '4k', 'gaming'],
    featured: true,
  },
  {
    id: '12',
    name: 'Sony A95L 55" QD-OLED TV',
    description: 'The pinnacle of picture quality with QD-OLED technology. Cognitive Processor XR delivers intense brightness, deep blacks, and over a billion colors.',
    price: 2999,
    originalPrice: 3499,
    category: 'TVs',
    brand: 'Sony',
    rating: 4.9,
    reviewCount: 178,
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800',
      'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=800',
    ],
    specifications: {
      'Display': '55" QD-OLED',
      'Resolution': '4K Ultra HD',
      'Processor': 'Cognitive Processor XR',
      'HDR': 'Dolby Vision, HDR10, HLG',
      'Refresh Rate': '120Hz',
      'Audio': 'Acoustic Surface Audio+',
    },
    tags: ['qd-oled', 'premium', '4k'],
    isNew: true,
  },
  {
    id: '13',
    name: 'Canon EOS R5',
    description: 'Revolutionary full-frame mirrorless camera with 45MP sensor, 8K video recording, and advanced Dual Pixel CMOS AF II for stunning results.',
    price: 3399,
    originalPrice: 3899,
    category: 'Cameras',
    brand: 'Canon',
    rating: 4.8,
    reviewCount: 412,
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
    ],
    specifications: {
      'Sensor': '45MP Full-Frame CMOS',
      'Video': '8K RAW, 4K 120p',
      'AF': 'Dual Pixel CMOS AF II',
      'Stabilization': 'In-body 5-axis',
      'Burst': 'Up to 20 fps',
      'Mount': 'Canon RF',
    },
    tags: ['professional', '8k', 'mirrorless'],
    featured: true,
  },
  {
    id: '14',
    name: 'Sony A7R V',
    description: 'High-resolution powerhouse with 61MP sensor, AI-based autofocus, and 8K video. The ultimate camera for professionals who demand exceptional detail.',
    price: 3899,
    originalPrice: 4199,
    category: 'Cameras',
    brand: 'Sony',
    rating: 4.9,
    reviewCount: 267,
    stock: 11,
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
    ],
    specifications: {
      'Sensor': '61MP Full-Frame Exmor R',
      'Video': '8K 24p, 4K 60p',
      'AF': 'AI-based Real-time Recognition',
      'Stabilization': '5.5-stop IBIS',
      'Viewfinder': '9.44M-dot OLED',
      'Mount': 'Sony E',
    },
    tags: ['professional', 'high-resolution', 'mirrorless'],
    isNew: true,
  },
  {
    id: '15',
    name: 'PlayStation 5 Slim',
    description: 'The slimmer PS5 with the same incredible gaming experience. Features ultra-high speed SSD, ray tracing, 4K gaming, and the DualSense controller.',
    price: 499,
    originalPrice: 549,
    category: 'Gaming',
    brand: 'Sony',
    rating: 4.8,
    reviewCount: 5234,
    stock: 67,
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b9453?w=800',
      'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?w=800',
    ],
    specifications: {
      'CPU': 'AMD Zen 2 8-core',
      'GPU': 'AMD RDNA 2 10.28 TFLOPs',
      'Storage': '1TB SSD',
      'Memory': '16GB GDDR6',
      'Output': '4K 120Hz, 8K',
      'Drive': '4K UHD Blu-ray',
    },
    tags: ['gaming', 'console', '4k'],
    featured: true,
  },
  {
    id: '16',
    name: 'Xbox Series X',
    description: 'The fastest, most powerful Xbox ever. Experience next-gen gaming with 12 TFLOPs of processing power, 1TB SSD, and native 4K gaming.',
    price: 499,
    originalPrice: 549,
    category: 'Gaming',
    brand: 'Microsoft',
    rating: 4.7,
    reviewCount: 4123,
    stock: 54,
    images: [
      'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800',
      'https://images.unsplash.com/photo-1605901309584-818e25960b8f?w=800',
    ],
    specifications: {
      'CPU': 'AMD Zen 2 8-core',
      'GPU': 'AMD RDNA 2 12 TFLOPs',
      'Storage': '1TB NVMe SSD',
      'Memory': '16GB GDDR6',
      'Output': '4K 120Hz, 8K',
      'Drive': '4K UHD Blu-ray',
    },
    tags: ['gaming', 'console', 'xbox'],
    featured: true,
  },
  {
    id: '17',
    name: 'Logitech MX Master 3S',
    description: 'The ultimate mouse for productivity with 8K DPI sensor, quiet clicks, and customizable buttons. Works on any surface, even glass.',
    price: 99,
    originalPrice: 129,
    category: 'Accessories',
    brand: 'Logitech',
    rating: 4.8,
    reviewCount: 2876,
    stock: 156,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800',
      'https://images.unsplash.com/photo-1615663245857-acda5b2b1587?w=800',
    ],
    specifications: {
      'DPI': 'Up to 8000',
      'Connectivity': 'Bluetooth, USB-C',
      'Battery': 'Up to 70 days',
      'Buttons': '7 programmable',
      'Scroll': 'MagSpeed electromagnetic',
      'Weight': '141g',
    },
    tags: ['productivity', 'wireless', 'ergonomic'],
    featured: true,
  },
  {
    id: '18',
    name: 'Keychron Q1 Pro',
    description: 'Premium wireless mechanical keyboard with full aluminum body, hot-swappable switches, and QMK/VIA support. The ultimate typing experience.',
    price: 199,
    originalPrice: 229,
    category: 'Accessories',
    brand: 'Keychron',
    rating: 4.7,
    reviewCount: 892,
    stock: 43,
    images: [
      'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    ],
    specifications: {
      'Layout': '75% (82 keys)',
      'Switches': 'Hot-swappable',
      'Connectivity': 'Bluetooth 5.1, USB-C',
      'Material': 'CNC Aluminum',
      'Keycaps': 'Double-shot PBT',
      'Features': 'QMK/VIA support, RGB',
    },
    tags: ['mechanical', 'wireless', 'custom'],
  },
];

// Mock Categories
export const categories: Category[] = [
  {
    id: '1',
    name: 'Laptops',
    description: 'Powerful laptops for work, gaming, and creativity',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
    productCount: 24,
  },
  {
    id: '2',
    name: 'Smartphones',
    description: 'Latest smartphones with cutting-edge technology',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400',
    productCount: 32,
  },
  {
    id: '3',
    name: 'Audio',
    description: 'Premium headphones, earbuds, and speakers',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    productCount: 45,
  },
  {
    id: '4',
    name: 'Tablets',
    description: 'Versatile tablets for productivity and entertainment',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400',
    productCount: 18,
  },
  {
    id: '5',
    name: 'Wearables',
    description: 'Smartwatches and fitness trackers',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400',
    productCount: 28,
  },
  {
    id: '6',
    name: 'Gaming',
    description: 'Consoles, controllers, and gaming accessories',
    image: 'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?w=400',
    productCount: 36,
  },
];

// Mock Reviews
export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userId: '1',
    userName: 'John D.',
    rating: 5,
    title: 'Best laptop I\'ve ever owned',
    comment: 'The M3 Max chip is incredibly fast. I use this for video editing and 3D rendering, and it handles everything I throw at it without breaking a sweat. The display is absolutely stunning.',
    createdAt: '2024-01-15',
    helpful: 234,
  },
  {
    id: '2',
    productId: '1',
    userId: '2',
    userName: 'Sarah M.',
    rating: 5,
    title: 'Worth every penny',
    comment: 'As a professional photographer, this MacBook has transformed my workflow. Lightroom and Photoshop run buttery smooth, and the battery life is incredible.',
    createdAt: '2024-01-10',
    helpful: 189,
  },
  {
    id: '3',
    productId: '5',
    userId: '3',
    userName: 'Mike R.',
    rating: 5,
    title: 'Best noise cancellation on the market',
    comment: 'I travel frequently for work, and these headphones are a game-changer. The noise cancellation is phenomenal, and the sound quality is exceptional.',
    createdAt: '2024-01-08',
    helpful: 156,
  },
  {
    id: '4',
    productId: '3',
    userId: '4',
    userName: 'Emily K.',
    rating: 4,
    title: 'Great phone, but expensive',
    comment: 'The iPhone 15 Pro Max is an excellent phone with amazing camera quality and performance. The titanium design feels premium. Only downside is the price.',
    createdAt: '2024-01-05',
    helpful: 98,
  },
  {
    id: '5',
    productId: '15',
    userId: '5',
    userName: 'Alex T.',
    rating: 5,
    title: 'Next-gen gaming is here',
    comment: 'The PS5 Slim is incredible. Load times are practically non-existent, and the games look stunning in 4K. The DualSense controller adds so much immersion.',
    createdAt: '2024-01-03',
    helpful: 267,
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'customer@example.com',
    name: 'John Customer',
    role: 'customer',
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    email: 'admin@techstore.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: '2024-01-01',
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: '1',
    items: [
      { productId: '1', name: 'MacBook Pro 16" M3 Max', price: 3499, quantity: 1, image: products[0].images[0] },
      { productId: '6', name: 'AirPods Pro (2nd Gen)', price: 249, quantity: 1, image: products[5].images[0] },
    ],
    subtotal: 3748,
    tax: 299.84,
    shipping: 0,
    total: 4047.84,
    status: 'delivered',
    shippingAddress: {
      id: '1',
      fullName: 'John Customer',
      street: '123 Main Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
      phone: '+1 555-123-4567',
    },
    paymentMethod: 'Credit Card',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-15',
  },
  {
    id: 'ORD-002',
    userId: '1',
    items: [
      { productId: '5', name: 'Sony WH-1000XM5', price: 349, quantity: 1, image: products[4].images[0] },
    ],
    subtotal: 349,
    tax: 27.92,
    shipping: 9.99,
    total: 386.91,
    status: 'shipped',
    shippingAddress: {
      id: '1',
      fullName: 'John Customer',
      street: '123 Main Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
      phone: '+1 555-123-4567',
    },
    paymentMethod: 'PayPal',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-20',
  },
];

// Helper functions
export const getProductById = (id: string): Product | undefined => {
  return products.find(p => p.id === id);
};

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter(p => p.category === category);
};

export const getFeaturedProducts = (): Product[] => {
  return products.filter(p => p.featured);
};

export const getNewProducts = (): Product[] => {
  return products.filter(p => p.isNew);
};

export const searchProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase();
  return products.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery) ||
    p.brand.toLowerCase().includes(lowerQuery) ||
    p.tags.some(t => t.toLowerCase().includes(lowerQuery))
  );
};

export const getProductReviews = (productId: string): Review[] => {
  return reviews.filter(r => r.productId === productId);
};

export const getAverageRating = (productId: string): number => {
  const productReviews = getProductReviews(productId);
  if (productReviews.length === 0) return 0;
  const sum = productReviews.reduce((acc, r) => acc + r.rating, 0);
  return Math.round((sum / productReviews.length) * 10) / 10;
};
